// <auto-generated />
using System;
using FunBooksAndVideos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FunBooksAndVideos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811192333_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FunBooksAndVideos.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 4567890,
                            Email = "john.doe@example.com",
                            IsActive = true,
                            Name = "John Doe"
                        });
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActivationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "Type")
                        .IsUnique();

                    b.ToTable("Memberships", (string)null);
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductKind")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasDiscriminator<string>("ProductKind").HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("PurchaseOrders", (string)null);
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.PurchaseOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_PurchaseOrderLines_ExactlyOneLineType", "([LineType] = 'Product' AND [ProductId] IS NOT NULL AND [MembershipType] IS NULL) OR ([LineType] = 'Membership' AND [ProductId] IS NULL AND [MembershipType] IS NOT NULL)");
                        });

                    b.HasDiscriminator<string>("LineType").HasValue("PurchaseOrderLine");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.Book", b =>
                {
                    b.HasBaseType("FunBooksAndVideos.Domain.Product");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasDiscriminator().HasValue("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "The Girl on the train",
                            Price = 14.99m,
                            Author = "Paula Hawkins",
                            Isbn = "9781234567897"
                        });
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.Video", b =>
                {
                    b.HasBaseType("FunBooksAndVideos.Domain.Product");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Video");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "Comprehensive First Aid Training",
                            Price = 33.51m,
                            Director = "John Smith",
                            DurationInMinutes = 0
                        });
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.MembershipOrderLine", b =>
                {
                    b.HasBaseType("FunBooksAndVideos.Domain.PurchaseOrderLine");

                    b.Property<string>("MembershipType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_PurchaseOrderLines_ExactlyOneLineType", "([LineType] = 'Product' AND [ProductId] IS NOT NULL AND [MembershipType] IS NULL) OR ([LineType] = 'Membership' AND [ProductId] IS NULL AND [MembershipType] IS NOT NULL)");
                        });

                    b.HasDiscriminator().HasValue("Membership");
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.ProductOrderLine", b =>
                {
                    b.HasBaseType("FunBooksAndVideos.Domain.PurchaseOrderLine");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasIndex("ProductId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_PurchaseOrderLines_ExactlyOneLineType", "([LineType] = 'Product' AND [ProductId] IS NOT NULL AND [MembershipType] IS NULL) OR ([LineType] = 'Membership' AND [ProductId] IS NULL AND [MembershipType] IS NOT NULL)");
                        });

                    b.HasDiscriminator().HasValue("Product");
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.Membership", b =>
                {
                    b.HasOne("FunBooksAndVideos.Domain.Customer", null)
                        .WithMany("Memberships")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.PurchaseOrder", b =>
                {
                    b.HasOne("FunBooksAndVideos.Domain.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.PurchaseOrderLine", b =>
                {
                    b.HasOne("FunBooksAndVideos.Domain.PurchaseOrder", null)
                        .WithMany("ItemLines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.ProductOrderLine", b =>
                {
                    b.HasOne("FunBooksAndVideos.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.Customer", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("FunBooksAndVideos.Domain.PurchaseOrder", b =>
                {
                    b.Navigation("ItemLines");
                });
#pragma warning restore 612, 618
        }
    }
}
